// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw7QwJYDACUH57GURgjJyMN4xuDpko_9c',
    appId: '1:655558659739:web:cdc7605af0732980d3c03e',
    messagingSenderId: '655558659739',
    projectId: 'fsspot-vendor-uer',
    authDomain: 'fsspot-vendor-uer.firebaseapp.com',
    storageBucket: 'fsspot-vendor-uer.firebasestorage.app',
    measurementId: 'G-FLS8EQG37M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1BBMOxRr5LFv1Biwnuz_t59fU_3SpH4k',
    appId: '1:655558659739:android:3a5ccfc969576de3d3c03e',
    messagingSenderId: '655558659739',
    projectId: 'fsspot-vendor-uer',
    storageBucket: 'fsspot-vendor-uer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD319dQBQ49a8OwaYBvqQoks-wc9DsiwcU',
    appId: '1:655558659739:ios:218388eeb14f94a0d3c03e',
    messagingSenderId: '655558659739',
    projectId: 'fsspot-vendor-uer',
    storageBucket: 'fsspot-vendor-uer.firebasestorage.app',
    iosBundleId: 'com.fsspot.fscourrier',
  );
}
